#pragma once

typedef enum {
	OK,
	ERROR_outofmemory,
	ERROR_handleclosed,
	ERROR_createdatabase,
	ERROR_createindex,
	ERROR_badhandle,
	ERROR_badrecid,
	ERROR_endoffile,
	ERROR_notbasever,
	ERROR_recorddeleted,
	ERROR_recordnotvisible,
	ERROR_notcurrentversion,
	ERROR_cursornotpositioned,
	ERROR_invaliddeleterecord,
	ERROR_cursorbasekeyerror,
	ERROR_cursoroverflow,
	ERROR_writeconflict,
	ERROR_duplicatekey,
	ERROR_keynotfound,
	ERROR_badtxnstep,
	ERROR_rollbackidxkey,
	ERROR_arena_already_closed,
	ERROR_script_internal,
	ERROR_script_unrecognized_function,
	ERROR_tcperror,
	ERROR_bsonformat,
	ERROR_notobject_or_array,
	ERROR_mathdomain,
	ERROR_keytoolong,
	ERROR_doesnot_exist,
	ERROR_btreepagelatchnotfound,
	ERROR_btreestruct,
	ERROR_arenadropped,
	ERROR_indextype,
	BTREE_needssplit,
	ARTREE_error,
} Status;

